In [8]:
import numpy as np

def solve_linear_equation(A, b):
    # enter your code here, and remove the following line (30%)
    rank_A = np.linalg.matrix_rank(A)
    A_b = np.hstack((A, b))# create [A, b]
    rank_A_b = np.linalg.matrix_rank(A_b)
    print("Rank(A) = ", rank_A, " Rank([A, b]) = ", rank_A_b)
    if rank_A == rank_A_b: # consistent
        if rank_A == A.shape[1]: # when rank_A == n
            return 1 # only one solution       
        else:
            return 0 # many solutions
    else: # not consistent, no solution
        return -1


def flag_to_message(flag):
    if flag == 1:
      print('The linear system Ax=b has only one solution.')
    elif flag == 0:
      print('The linear system Ax=b has infinitely many solutions.')
    elif flag == -1:
      print('The linear system Ax=b has no solutions.')
    else:
      print('Unknown flag!')

def get_input_data(input_id):
    if input_id == 'case1': 
      A = np.array([[3, 2, -1], [6, -1, 3], [1, 10, -2]])
      b = np.array([[-7], [-4], [2]])
    elif input_id == 'case2':
      A = np.array([[4, -1, 3], [21, -4, 18], [-9, 1, -9]])
      b = np.array([[5], [7], [-8]])
    elif input_id == 'case3':
      A = np.array([[7, -4, 1], [3, 2, -1], [5, 12, -5]])
      b = np.array([[-15], [-5], [-5]])
    return A, b

if __name__ == '__main__':
    for case in ['case1', 'case2', 'case3']:
      A, b = get_input_data(case)
      print(case)
      print('A =', A, 'b =', b.T)
      flag = solve_linear_equation(A, b)
      flag_to_message(flag)
      if flag == 1:
        print('The solution is ', np.linalg.solve(A, b))
      print()


case1
A = [[ 3  2 -1]
 [ 6 -1  3]
 [ 1 10 -2]] b = [[-7 -4  2]]
Rank(A) =  3  Rank([A, b]) =  3
The linear system Ax=b has only one solution.
The solution is  [[-2.]
 [ 1.]
 [ 3.]]

case2
A = [[ 4 -1  3]
 [21 -4 18]
 [-9  1 -9]] b = [[ 5  7 -8]]
Rank(A) =  2  Rank([A, b]) =  3
The linear system Ax=b has no solutions.

case3
A = [[ 7 -4  1]
 [ 3  2 -1]
 [ 5 12 -5]] b = [[-15  -5  -5]]
Rank(A) =  2  Rank([A, b]) =  2
The linear system Ax=b has infinitely many solutions.



Test `np.linalg.matrix_rank()`

In [9]:
a = np.array([[2, 2],
              [3, 4]])
b = np.array([[2, 2],
              [3, 3]])
print(np.linalg.matrix_rank(a))
print(np.linalg.matrix_rank(b))


2
1


In [10]:
# Can we use np.linalg.solve() to determine whether 𝐀𝐱=𝐛 is consistent? Explain the reason for your answer. (5%)
# Write down your answer here.

########### ANS ################
# No, we can't.
# Based on above result, case3 has many solutions, and it is consistent. So, I want to test if it can get solutions from `np.linalg.solve` function.
A, b = get_input_data("case3") # A is singular matrix.
print('A =', A, 'b =', b.T)
# np.linalg.solve(A, b)
# Above solve function will raise error because A as np.linalg.solve's parameter shouldn't be singular matrix.
# We know both case1 and case3 are consistent, but case3 can't be applied to `np.linalg.solve` function.
# Hence, we can't use `np.linalg.solve` to determine whether 𝐀𝐱=𝐛 is consistent

A = [[ 7 -4  1]
 [ 3  2 -1]
 [ 5 12 -5]] b = [[-15  -5  -5]]


In [11]:
# Given matrix 𝐀 of dimension (m,n). If rank(𝐀)=𝑛, can we infer that 𝐀𝐱=𝐛 is consistent? Explain the reason for your answer. (5%)
# Write down your answer here.

########### ANS ################
# The answer depends on if m is equal to n, so I will divide into 2 situations:
# If m == n,
    # Yes, we can.
    # If rank(A) is n, A is non-singular matrix which is invertible. Therefore, we can calculate the unique solution x by x = A^{-1}b, which means Ax=b is consistent.

# If m != n,
    # No, we can't. The consistency should depend on b.
    # rank(A) means that the columns of A are linearly independent, and the system 𝐀𝐱=𝐛 will be consistent if and only if b lies within the column space of A.